// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqoajlefblgtveatxsqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxb2FqbGVmYmxndHZlYXR4c3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTU4NDQsImV4cCI6MjA3Mjk5MTg0NH0.fdP2Ig3nYdjKJQ33oY2_lE9a8IQZdd5p-YsbHT3OMiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});